/*
 * motor.c
 *
 *  Created on: Apr 28, 2024
 *      Author: Adham
 */



#include "motor_Interf.h"

void Stop(){
	HAL_GPIO_WritePin(IN1_DIRECTION_MOTOR_GPIO_Port, IN1_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN2_DIRECTION_MOTOR_GPIO_Port, IN2_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN3_DRIVE_MOTOR_GPIO_Port, IN3_DRIVE_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN4_DRIVE_MOTOR_GPIO_Port, IN4_DRIVE_MOTOR_Pin, GPIO_PIN_RESET);
}

void Forward(){
	/* IN3 = 1 , IN4 = 0*/
	HAL_GPIO_WritePin(IN3_DRIVE_MOTOR_GPIO_Port, IN3_DRIVE_MOTOR_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(IN4_DRIVE_MOTOR_GPIO_Port, IN4_DRIVE_MOTOR_Pin, GPIO_PIN_RESET);

	/*IN1 = 0 , IN2 = 0*/
	// Stopping the front motor
	HAL_GPIO_WritePin(IN1_DIRECTION_MOTOR_GPIO_Port, IN1_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN2_DIRECTION_MOTOR_GPIO_Port, IN2_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);
}

void Backward(){


	/*IN3 = 0 , IN4 = 1*/
	HAL_GPIO_WritePin(IN3_DRIVE_MOTOR_GPIO_Port, IN3_DRIVE_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN4_DRIVE_MOTOR_GPIO_Port, IN4_DRIVE_MOTOR_Pin, GPIO_PIN_SET);



	/*IN1 = 0 , IN2 = 0*/
	// Stopping the front motor
	HAL_GPIO_WritePin(IN1_DIRECTION_MOTOR_GPIO_Port, IN1_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN2_DIRECTION_MOTOR_GPIO_Port, IN2_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);

}

void Right(){

	/*IN1 = 1 , IN2 = 0*/
	HAL_GPIO_WritePin(IN1_DIRECTION_MOTOR_GPIO_Port, IN1_DIRECTION_MOTOR_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(IN2_DIRECTION_MOTOR_GPIO_Port, IN2_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);

	/* IN3 = 1 , IN4 = 0*/
	HAL_GPIO_WritePin(IN3_DRIVE_MOTOR_GPIO_Port, IN3_DRIVE_MOTOR_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(IN4_DRIVE_MOTOR_GPIO_Port, IN4_DRIVE_MOTOR_Pin, GPIO_PIN_RESET);

}

void Left(){

	/*IN1 = 0 , IN2 = 1*/
	HAL_GPIO_WritePin(IN1_DIRECTION_MOTOR_GPIO_Port, IN1_DIRECTION_MOTOR_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(IN2_DIRECTION_MOTOR_GPIO_Port, IN2_DIRECTION_MOTOR_Pin, GPIO_PIN_SET);

	/* IN3 = 1 , IN4 = 0*/
	HAL_GPIO_WritePin(IN3_DRIVE_MOTOR_GPIO_Port, IN3_DRIVE_MOTOR_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(IN4_DRIVE_MOTOR_GPIO_Port, IN4_DRIVE_MOTOR_Pin, GPIO_PIN_RESET);

}
